# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos"
github_repo = "siderolabs/talos"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.2.2"

pre_release = true

preface = """\
"""

[notes]

    [notes.kernel_modules]
        title = "Kernel Modules"
        description = """\
Talos now supports settings kernel module parameters.

Eg:

```yaml
machine:
  kernel:
    modules:
      - name: "br_netfilter"
        parameters:
          - nf_conntrack_max=131072
```
"""

    [notes.sbc]
        title = "Nano Pi R4S"
        description = """\
Talos now supports the Nano Pi R4S SBC.
"""

    [notes.sbc1]
        title = "Raspberry Generic Images"
        description = """\
The Raspberry Pi 4 specific image has been deprecated and will be removed in the v1.4 release of Talos.
Talos now ships a generic Raspberry Pi image that should support more Raspberry Pi variants.
Refer to the docs at https://www.talos.dev/v1.3/talos-guides/install/single-board-computers/rpi_generic/ to find which ones are supported.
"""

    [notes.updates]
        title = "Component Updates"
        description="""\
* Kubernetes: v1.26.0-alpha.1
* Flannel: v0.19.2
* CoreDNS: v1.10.0
* etcd: v3.5.5
* Linux: 5.15.70
"""

    [notes.etcd]
        title = "etcd Consistency Check"
        description="""\
Talos enables [--experimental-compact-hash-check-enabled](https://github.com/etcd-io/etcd/pull/14120) option by default to improve
etcd store consistency guarantees.

This options is only available with etcd >= v3.5.5, so Talos doesn't support version of etcd before v3.5.5.
"""

    [notes.auditpolicy]
        title = "kube-apiserver Audit Policy"
        description="""\
Talos now supports setting custom audit policy for `kube-apiserver` in the machine configuration.
"""

[make_deps]

    [make_deps.tools]
        variable = "TOOLS"
        repository = "github.com/siderolabs/tools"

    [make_deps.pkgs]
        variable = "PKGS"
        repository = "github.com/siderolabs/pkgs"

    [make_deps.extras]
        variable = "EXTRAS"
        repository = "github.com/siderolabs/extras"
